/*
-- Query: SELECT * FROM colegio_pablo_neruda.dimrepresentantes
LIMIT 0, 1000

-- Date: 2021-12-07 02:19
*/
INSERT INTO `` (`IdRepresentante`,`NombreMadre`,`NombrePadre`,`DNIMadre`,`DNIPadre`,`ProfesionMadre`,`ProfesionPadre`,`CorreoMadre`,`CorreoPadre`,`DireccionVivienda`,`LugarTrabajoMadre`,`LugarTrabajoPadre`) VALUES (1,'Laura Torres','Jose Linares',30505828,32674947,'Doctora','Mecanico','laura23@gmail.com',NULL,'Palermo 234 CABA','Hospital Italiano','Caballito Rivadavia 2333 CABA');
INSERT INTO `` (`IdRepresentante`,`NombreMadre`,`NombrePadre`,`DNIMadre`,`DNIPadre`,`ProfesionMadre`,`ProfesionPadre`,`CorreoMadre`,`CorreoPadre`,`DireccionVivienda`,`LugarTrabajoMadre`,`LugarTrabajoPadre`) VALUES (2,'Cecilia Rodriguez','Rodolfo Rangel',35565848,35829572,'Profesora','Ingeniero','ceciro@gmail.com','rodo@gmail.com','Julian A 1988 CABA','Colegio Independencia','Mercado Libre');
INSERT INTO `` (`IdRepresentante`,`NombreMadre`,`NombrePadre`,`DNIMadre`,`DNIPadre`,`ProfesionMadre`,`ProfesionPadre`,`CorreoMadre`,`CorreoPadre`,`DireccionVivienda`,`LugarTrabajoMadre`,`LugarTrabajoPadre`) VALUES (3,'Maria Tintero','Cesar Teran',32035498,45395297,'Ingeniera ','Doctor','maritintero@gmail.com','cesarto@gmail.com','Rivadavia 35 CABA','Accenture','Clinica San Jose');
INSERT INTO `` (`IdRepresentante`,`NombreMadre`,`NombrePadre`,`DNIMadre`,`DNIPadre`,`ProfesionMadre`,`ProfesionPadre`,`CorreoMadre`,`CorreoPadre`,`DireccionVivienda`,`LugarTrabajoMadre`,`LugarTrabajoPadre`) VALUES (4,'Andrea Soto','Francisco Miranda',55782756,54928503,'Profesora','Abogado','andto@gmail.com','miranda@gmail.com','Venezuela 544 CABA','Colegio MariaLourdes','Abogados360');
INSERT INTO `` (`IdRepresentante`,`NombreMadre`,`NombrePadre`,`DNIMadre`,`DNIPadre`,`ProfesionMadre`,`ProfesionPadre`,`CorreoMadre`,`CorreoPadre`,`DireccionVivienda`,`LugarTrabajoMadre`,`LugarTrabajoPadre`) VALUES (5,'Estefany Gonzalez','Gonzalo Gutierrez',45392759,42395829,'Abogada','Abogado','tefagon34@gmail.com','gonzagonz@gmail.com','Santa Fe 2222 CABA','Hermanos Asociados','Atencion legal CABA');
INSERT INTO `` (`IdRepresentante`,`NombreMadre`,`NombrePadre`,`DNIMadre`,`DNIPadre`,`ProfesionMadre`,`ProfesionPadre`,`CorreoMadre`,`CorreoPadre`,`DireccionVivienda`,`LugarTrabajoMadre`,`LugarTrabajoPadre`) VALUES (6,'Laura Fernandez','Wilfredo Perez',29534760,30929238,'Enfermera','Doctor','lalafe@gmail.com','wilfr@gmail.com','Honduras 245 CABA','Hospital Rivadavia','Hospital Italiano');
INSERT INTO `` (`IdRepresentante`,`NombreMadre`,`NombrePadre`,`DNIMadre`,`DNIPadre`,`ProfesionMadre`,`ProfesionPadre`,`CorreoMadre`,`CorreoPadre`,`DireccionVivienda`,`LugarTrabajoMadre`,`LugarTrabajoPadre`) VALUES (7,'Marisa Gutierrez','Ricardo Montaner',37850245,36593056,'Doctora','Mecanico','marisa1999@gmail.com','kkferl@gmail.com','Belgrano 345 CABA','Hominis','Renault 345 CABA');
INSERT INTO `` (`IdRepresentante`,`NombreMadre`,`NombrePadre`,`DNIMadre`,`DNIPadre`,`ProfesionMadre`,`ProfesionPadre`,`CorreoMadre`,`CorreoPadre`,`DireccionVivienda`,`LugarTrabajoMadre`,`LugarTrabajoPadre`) VALUES (8,'Daniela Rodriguez','Kell Fernandez',30491848,31094857,'Ingeniera ','Chofer','danirodri@gmail.com','osw@gmail.com','Palermo 4555 CABA','Mercado Libre','Cabify');
INSERT INTO `` (`IdRepresentante`,`NombreMadre`,`NombrePadre`,`DNIMadre`,`DNIPadre`,`ProfesionMadre`,`ProfesionPadre`,`CorreoMadre`,`CorreoPadre`,`DireccionVivienda`,`LugarTrabajoMadre`,`LugarTrabajoPadre`) VALUES (9,'Maria Marchena','Oswaldo Duval',45545989,43857927,'Vendedora','Encargado','marchena4@gmail.com','duvalos@gmail.com','Colon 565 CABA','Alto Palermo','Hells Pizza');
INSERT INTO `` (`IdRepresentante`,`NombreMadre`,`NombrePadre`,`DNIMadre`,`DNIPadre`,`ProfesionMadre`,`ProfesionPadre`,`CorreoMadre`,`CorreoPadre`,`DireccionVivienda`,`LugarTrabajoMadre`,`LugarTrabajoPadre`) VALUES (10,'Valentina Tillero','Ricardo Leon',56878927,56929458,'Ingeniera ','Ingeniero','valentinatille@gmail.com','leonricardo@gmail.com','Loyola 256 CABA','Accenture','Accenture');
INSERT INTO `` (`IdRepresentante`,`NombreMadre`,`NombrePadre`,`DNIMadre`,`DNIPadre`,`ProfesionMadre`,`ProfesionPadre`,`CorreoMadre`,`CorreoPadre`,`DireccionVivienda`,`LugarTrabajoMadre`,`LugarTrabajoPadre`) VALUES (11,'Angelica Fuentes','Gabriel Phyllis ',39666824,48496737,'Ingeniera ','Ingeniero',NULL,NULL,'Lavalleja 2510 CABA','Litora Torquent LLC','Libero Integer PC');
INSERT INTO `` (`IdRepresentante`,`NombreMadre`,`NombrePadre`,`DNIMadre`,`DNIPadre`,`ProfesionMadre`,`ProfesionPadre`,`CorreoMadre`,`CorreoPadre`,`DireccionVivienda`,`LugarTrabajoMadre`,`LugarTrabajoPadre`) VALUES (12,'Risa Newman','Hedley Hawkins',21556536,29401635,'Abogada','Ingeniero',NULL,'risi@gmail.com','Valle 200 CABA','Tristique Asociados','Penatibus PC');
INSERT INTO `` (`IdRepresentante`,`NombreMadre`,`NombrePadre`,`DNIMadre`,`DNIPadre`,`ProfesionMadre`,`ProfesionPadre`,`CorreoMadre`,`CorreoPadre`,`DireccionVivienda`,`LugarTrabajoMadre`,`LugarTrabajoPadre`) VALUES (13,'Gloria Martina','Victor Morales',42892493,49369889,'Vendedora','Comerciante',NULL,'glr@gmail.com','Echeverria 1200 CABA','Mollis Dui LLC','Duis At LLC');
INSERT INTO `` (`IdRepresentante`,`NombreMadre`,`NombrePadre`,`DNIMadre`,`DNIPadre`,`ProfesionMadre`,`ProfesionPadre`,`CorreoMadre`,`CorreoPadre`,`DireccionVivienda`,`LugarTrabajoMadre`,`LugarTrabajoPadre`) VALUES (14,'Ann Isabella','no tiene',23829399,NULL,'Analista',NULL,'an@gmail.com',NULL,'Gascon 1500 CABA','Lectus Corp.',NULL);
INSERT INTO `` (`IdRepresentante`,`NombreMadre`,`NombrePadre`,`DNIMadre`,`DNIPadre`,`ProfesionMadre`,`ProfesionPadre`,`CorreoMadre`,`CorreoPadre`,`DireccionVivienda`,`LugarTrabajoMadre`,`LugarTrabajoPadre`) VALUES (15,'Camila Garrett ','Vernon Diaz',30727203,47682129,'Economista','Telefonista',NULL,'ve@gmail.com','Rivadavia 345 CABA','Telefonica','Telefonica');
INSERT INTO `` (`IdRepresentante`,`NombreMadre`,`NombrePadre`,`DNIMadre`,`DNIPadre`,`ProfesionMadre`,`ProfesionPadre`,`CorreoMadre`,`CorreoPadre`,`DireccionVivienda`,`LugarTrabajoMadre`,`LugarTrabajoPadre`) VALUES (16,'no tiene','Luis Inez ',NULL,49113665,NULL,'Economista',NULL,'lus@gmail.com','Mario Bravo 1110 CABA',NULL,'Galicia');
INSERT INTO `` (`IdRepresentante`,`NombreMadre`,`NombrePadre`,`DNIMadre`,`DNIPadre`,`ProfesionMadre`,`ProfesionPadre`,`CorreoMadre`,`CorreoPadre`,`DireccionVivienda`,`LugarTrabajoMadre`,`LugarTrabajoPadre`) VALUES (17,'Norman Silva','Len Torres',27887446,18994961,'Ambiental','Ingeniero','ja@gmail.com',NULL,'Scalabrini Ortiz 2500 CABA','Jardin Japones','Consultora EY');
INSERT INTO `` (`IdRepresentante`,`NombreMadre`,`NombrePadre`,`DNIMadre`,`DNIPadre`,`ProfesionMadre`,`ProfesionPadre`,`CorreoMadre`,`CorreoPadre`,`DireccionVivienda`,`LugarTrabajoMadre`,`LugarTrabajoPadre`) VALUES (18,'Sandra Pascal','no tiene',50489875,39258573,'Jardinera','Mesero','hag@gmail.com',NULL,'Aguirre 100 CABA','Jardin Botanico','La Clotilde');
INSERT INTO `` (`IdRepresentante`,`NombreMadre`,`NombrePadre`,`DNIMadre`,`DNIPadre`,`ProfesionMadre`,`ProfesionPadre`,`CorreoMadre`,`CorreoPadre`,`DireccionVivienda`,`LugarTrabajoMadre`,`LugarTrabajoPadre`) VALUES (19,'Keelie Soto','Erich Garcia',35595348,36114212,'Chef','Profesor','rg@gmail.com',NULL,'Juan B Justo 1100 CABA','Hard Rock','Colegio Maria Auxiliadora');
INSERT INTO `` (`IdRepresentante`,`NombreMadre`,`NombrePadre`,`DNIMadre`,`DNIPadre`,`ProfesionMadre`,`ProfesionPadre`,`CorreoMadre`,`CorreoPadre`,`DireccionVivienda`,`LugarTrabajoMadre`,`LugarTrabajoPadre`) VALUES (20,'Catalina Keefe ',' Juan Lucius',17469452,42171944,'Masajista','Profesor','tgv@gmail.com',NULL,'Soler 502 CABA','Espacio Glam','Colegio Maria Auxiliadora');
INSERT INTO `` (`IdRepresentante`,`NombreMadre`,`NombrePadre`,`DNIMadre`,`DNIPadre`,`ProfesionMadre`,`ProfesionPadre`,`CorreoMadre`,`CorreoPadre`,`DireccionVivienda`,`LugarTrabajoMadre`,`LugarTrabajoPadre`) VALUES (21,'Valeria Echeverria','Gonzalo Zapata',23333333,43333333,'Doctora','Doctor','doct@gmail.com',NULL,'Guatemala 5500 CABA','Hospital Britanico','Clinica San Jose');
INSERT INTO `` (`IdRepresentante`,`NombreMadre`,`NombrePadre`,`DNIMadre`,`DNIPadre`,`ProfesionMadre`,`ProfesionPadre`,`CorreoMadre`,`CorreoPadre`,`DireccionVivienda`,`LugarTrabajoMadre`,`LugarTrabajoPadre`) VALUES (22,'Nancy Jimenez','Jesus Sirverg',77777777,55555555,'Coordinadora Eventos','Freelance',NULL,NULL,'Honduras 4500 CABA','Eventos Loyola',NULL);
